### ISSUE TITLE
NSE Nov 01

### ISSUE THREAD

**Issue by RS-NDIND** [hemenkapadia/getbhavcopy#212]
Am unable to d/load data from NSE. 
Has anyone else also faced problems downloading today's data?

This problem is restricted to data for Nov 01 only.

Data for prior dates is being downloaded.  So most likely this is a problem at NSE end and not an issue with the GetBhavCopy application.
.
.
![image](https://user-images.githubusercontent.com/54636605/199301308-095f6403-520c-49d6-9a61-4b97cbd75c4c.png)

**Comment by Rvgandhi** [comment]
Facing the same issue ; Data not downloading from NSE for 01 Nov 2022

**Comment by bijoy2526** [comment]
yes same problem here too.can any one provide datas for amiborker for yesterday,

**Comment by karan1961** [comment]
Yes, facing same problem for 1 st Nov 2022

**Comment by karan1961** [comment]
But Yes, some of the index data is downloading..

**Comment by karan1961** [comment]
I think it is an issue with NSE server.

**Comment by Rvgandhi** [comment]
Similar problem was faced on 1 Nov 2021 ; last year

**Comment by karan1961** [comment]
NSE has not uploaded bhavcopy. So this is the issue i guess.

**Comment by shyam027** [comment]
Yes, I am also facing the same issue, I am not sure why such an issue from NSE....will they upload the bhavcopy after some time?

**Comment by morphu77** [comment]
the bhavcopy data is available on NSE but its not getting downloaded on getbhavcopy for today and yesterday . 

https://www.nseindia.com/all-reports

**Comment by madhanji** [comment]
Dear Hemen.
from NOV 01.2022 WE ARE unable to download from both NSE server...
but server working well,one member tried with C# code and its downloading as usual.

so kindly check and help us

**Comment by rbalu72** [comment]
+1  1-Nov-22 onwards data not getting downloaded for NSE
It could be a change of source or where the bhavcopy is available on NSE.

**Comment by UDAY220167** [comment]
nse old site has not uploaded file for 01112022 you will get it on new site but not working with getbhavcopy even after changing to new nsesite setting in getbhavcopy

**Comment by rajbrs** [comment]
Facing same problem since yesterday.

**Comment by MSurenBabu** [comment]
Me too. It is not working since yesterday. Request to fix it.

**Comment by RS-NDIND** [comment]
![image](https://user-images.githubusercontent.com/54636605/199555246-578d08e5-d64c-41fd-83a5-92de93c48fb1.png)

#1 Server selection changed to new server. Application restarted.

#2 Request aborted. Connection closed.

**Comment by htc121** [comment]
Looks lije name of the bhavcopy file has hanged. https://archives.nseindia.com/products/content/sec_bhavdata_full_02112022.csv
Also the fields have changed.

**Comment by htc121** [comment]
NSE EQ data for 1st and 2nd NOv 2022 for Amibroker

[2022-11-01-NSE-EQ.csv](https://github.com/hemenkapadia/getbhavcopy/files/9923104/2022-11-01-NSE-EQ.csv)
[2022-11-02-NSE-EQ.csv](https://github.com/hemenkapadia/getbhavcopy/files/9923105/2022-11-02-NSE-EQ.csv)

**Comment by bijoy2526** [comment]
showing error
![image](https://user-images.githubusercontent.com/54546802/199634883-78e79803-8d30-4a72-899f-07d890054570.png)

**Comment by bijoy2526** [comment]
htc121 kindly help.

**Comment by bijoy2526** [comment]
any body can help? close is not negetive.

**Comment by bijoy2526** [comment]
![image](https://user-images.githubusercontent.com/54546802/199637357-d20e879c-cc26-4756-b8c4-a1918e6c28fd.png)

**Comment by kartikppatil411** [comment]
[01 NOV 22.txt](https://github.com/hemenkapadia/getbhavcopy/files/9925455/01.NOV.22.txt)
[02 NOV 22.txt](https://github.com/hemenkapadia/getbhavcopy/files/9925457/02.NOV.22.txt)
NSE EQ data for 1st and 2nd NOv 2022 for Amibroker

**Comment by bijoy2526** [comment]
sorry bro not working.

**Comment by Swajo23** [comment]
[20221102 alll.txt](https://github.com/hemenkapadia/getbhavcopy/files/9926333/20221102.alll.txt)
[20221101 all.txt](https://github.com/hemenkapadia/getbhavcopy/files/9926335/20221101.all.txt)

**Comment by Swajo23** [comment]
Please try this

**Comment by bijoy2526** [comment]
@Swajo23 ,not working bro.

**Comment by UDAY220167** [comment]
txt and csv both the file working

**Comment by UDAY220167** [comment]
for metastock in csv you have to change the date col in ddmmyyyy instead yyyymmdd
it will work for metastock also

**Comment by morphu77** [comment]
@Swajo23 Thanks bro . Working for my processor . Request you to Please upload these daily files till this issue is fixed

**Comment by bijoy2526** [comment]
@UDAY220167 ,working?I have not changed any setting.why in my case it is not working.
![image](https://user-images.githubusercontent.com/54546802/199711546-42ce93e0-24ba-4eae-b7c2-0f2893239ac9.png)

**Comment by RS-NDIND** [comment]
Update #1 

After two days of not functioning, today thankfully GBC application was able to successfully download.

I am using the same version of GBC that I was using on November 01. 

So it is OBVIOUS that the problem was NOT at our end insofar as using the old NSE server is concerned. The application was/is  not able to connect to the new server. The application developer will know best what is the reason for this.

Now the funny bit, even though I was able to d/load today's file, I am not able to download the files for Nov 01 and Nov 02. As mentioned in the OP, I was able to d/l data for Oct 31 and prior. So the data is not available for Nov 01 and Nov 02. Data is available prior and subsequent to these dates.

Final takeaway? NSE employees are incompetent. They are not able to do their job properly. They should be either fired or the oversight on them tightened.

**Comment by RS-NDIND** [comment]
Update #2 

Was able to d/load data for Nov 01 and Nov 02. 

Index data still not being d/loaded for these two dates.

**Comment by Rvgandhi** [comment]
Index data not downloaded for 01 and 02 November ; For today, I was able to download the data.

I recollect similar experience last year on 1/2 November 2021

**Comment by rajbrs** [comment]
Now it is working & data for 1-2 Nov also downloaded. Index data missing for 1-2 Nov.

**Comment by niravshah74** [comment]
Error and not downloading 1,2 and 3rd november........ it may continue till bugs are not removed......so do needful. Thanking you

**Comment by htc121** [comment]
[2022-11-03-NSE-EQ.csv](https://github.com/hemenkapadia/getbhavcopy/files/9932229/2022-11-03-NSE-EQ.csv)
NSE Equity data only for 3rd Nov 2022( For Amibroker)

**Comment by RS-NDIND** [comment]
> Error and not downloading 1,2 and 3rd november........ it may continue till bugs are not removed......so do needful. Thanking you

There are NO repeat No bugs in GBC. The fact that it is working without any errors for period before Nov 01 and after Nov 02, establishes that the software is working as intended without repeat without errors.

The problem is with the incompetent employees of NSE.

If some one can share the following information (1) relevant files names which contain index data ,(2) the path from which the GBC software downloads the relevant files, (3) the permissions  if any that are used to d/load data from NSE servers by GBC and (4) contact person if any is known, I will take up the matter with them.

**Comment by bijoy2526** [comment]
data of 4th is downloading.But we have misses the index datas of 1 st and 2nd november.

**Comment by MSurenBabu** [comment]
Yes, it is working now except Nov 1 & 2 indices data. Can anyone share that missing data if you have. This is a great tool which i use everyday for past many years. Thanks to the author for the far sighted view to create it.

**Comment by Swajo23** [comment]
Dear Bijoy ..

Attached TXT file working with Metastock Converter...

Regards

**Comment by bijoy2526** [comment]
@Swajo23 ,thanks will try.

**Comment by madhanji** [comment]
yesterday evening onwards its working well and download 1,2 nov index data also

**Comment by bijoy2526** [comment]
thanks

**Comment by iMakeBid** [comment]
https://github.com/iMakeBid/BID/issues/1#issuecomment-1579134275
